# Site
title:              cosmoquester's Blog
bio:                'I am collegian junior of SungKyunKwan University in Korea. I am majoring in Software. Thank you.'
description:        'I am collegian junior of SungKyunKwan University in Korea. I am majoring in Software. Thank you.'
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://cosmoquester.github.io
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:
utterances_repo_name: cosmoquester/blog-comments

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        G-97ZXEQTTPZ
  verify:
  #ad-client:
  #ad-slot:
naver:
  analytics:        1a77e23471cac20
#bing-verify:
email:              cosmoquester@gmail.com
#twitter:            username
facebook:           cosmoquester
github-url:         cosmoquester
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          cosmoquester
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
blog:               https://evols-atirev.tistory.com/

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: ''

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
